CLICKHOUSE_HOST = "192.168.247.128"
CLICKHOUSE_PORT = 8123
CLICKHOUSE_DATABASE = "telecom_analytics"
CLICKHOUSE_USERNAME = "default"
CLICKHOUSE_PASSWORD = ""

CONNECTION_TIMEOUT = 30  # seconds
QUERY_TIMEOUT = 10  # seconds